import 'dart:convert';

class QrParseResult {
  final bool isValid;
  final String? type;
  final String? id;
  final String? code;
  final String? errorMessage;

  QrParseResult({
    required this.isValid,
    this.type,
    this.id,
    this.code,
    this.errorMessage,
  });
}

class QrService {
  /// Parses QR code data generated by the backend.
  /// Expected JSON format:
  /// {
  ///   "type": "customer_location" | "robot" | "vehicle",
  ///   "id": "uuid",
  ///   "code": "CUST-001"
  /// }
  static QrParseResult parseQrData(String rawData) {
    try {
      final data = jsonDecode(rawData) as Map<String, dynamic>;

      final type = data['type'] as String?;
      if (type == null) {
        return QrParseResult(isValid: false, errorMessage: 'Missing "type" in QR code');
      }

      // Accept all valid QR types from the backend
      const validTypes = [
        'customer_location',  // Generated on customer QR
        'robot_deploy',       // Generated on robot QR
        'robot_return',       // Used when returning robot
        'vehicle_return',     // Generated on vehicle QR
        'robot',              // Legacy
        'vehicle',            // Legacy
      ];
      if (!validTypes.contains(type)) {
        return QrParseResult(isValid: false, errorMessage: 'Unknown QR type: $type');
      }

      final id = data['id'] as String?;
      if (id == null || id.isEmpty) {
        return QrParseResult(isValid: false, errorMessage: 'Missing "id" in QR code');
      }

      return QrParseResult(
        isValid: true,
        type: type,
        id: id,
        code: data['code'] as String?,
      );
    } catch (e) {
      return QrParseResult(isValid: false, errorMessage: 'Invalid QR code format');
    }
  }
}
